[package]
name = "schnorr_account_contract"
authors = [""]
compiler_version = ">=0.18.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.21.0", directory = "yarn-project/aztec-nr/aztec" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.21.0", directory = "yarn-project/aztec-nr/authwit" }
field_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.21.0", directory = "yarn-project/aztec-nr/field-note"}
