
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  AztecAddressLike,
  CompleteAddress,
  Contract,
  ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  ContractMethod,
  DeployMethod,
  EthAddress,
  EthAddressLike,
  FieldLike,
  Fr,
  FunctionSelectorLike,
  loadContractArtifact,
  NoirCompiledContract,
  Point,
  PublicKey,
  Wallet,
} from '@aztec/aztec.js';
import StorageContractContractArtifactJson from '../proxy_storage/target/proxy_storage-StorageContract.json' assert { type: 'json' };
export const StorageContractContractArtifact = loadContractArtifact(StorageContractContractArtifactJson as NoirCompiledContract);

/**
 * Type-safe interface for contract StorageContract;
 */
export class StorageContractContract extends ContractBase {
  
  private constructor(
    completeAddress: CompleteAddress,
    wallet: Wallet,
    portalContract = EthAddress.ZERO
  ) {
    super(completeAddress, StorageContractContractArtifact, wallet, portalContract);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, StorageContractContract.artifact, wallet) as Promise<StorageContractContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<StorageContractContract>(Point.ZERO, wallet, StorageContractContractArtifact, StorageContractContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public key to derive the address.
   */
  public static deployWithPublicKey(publicKey: PublicKey, wallet: Wallet, ) {
    return new DeployMethod<StorageContractContract>(publicKey, wallet, StorageContractContractArtifact, StorageContractContract.at, Array.from(arguments).slice(2));
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return StorageContractContractArtifact;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public methods!: {
    
    /** compute_note_hash_and_nullifier(contract_address: struct, nonce: field, storage_slot: field, serialized_note: array) */
    compute_note_hash_and_nullifier: ((contract_address: AztecAddressLike, nonce: FieldLike, storage_slot: FieldLike, serialized_note: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_counter() */
    get_counter: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_public_counter() */
    get_public_counter: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_counter(old_count: field, new_count: field) */
    update_counter: ((old_count: FieldLike, new_count: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_address(address: struct) */
    get_address: ((address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_public_counter(old_count: field, new_count: field) */
    update_public_counter: ((old_count: FieldLike, new_count: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_address(address: struct, value: boolean) */
    update_address: ((address: AztecAddressLike, value: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };
}
